#!/usr/bin/env python3

##############################################
## IMPORTS
##############################################

from sys import argv
from re import findall
from collections import Counter
from operator import itemgetter
from os import system

##############################################
## DEFINITIONS
##############################################

# read supplied file a line at a time pulling out valid ips from sshd lines
def search(lines):
    for line in open(argv[1]):
        if 'Bad protocol version identification' in line or 'Did not receive identification string from' in line or 'Invalid user admin from' in line:
            lines.append(line)

# pull out ip addresses
def cutips(lines):
    for i in range(len(lines)):
        ip = findall( r'[0-9]+(?:\.[0-9]+){3}', lines[i] )
        lines[i] = ip

# get rid of internal lists
def dumplist(lines):
    linestemp = []
    for i in range(len(lines)):
        linestemp.append(lines[i][0])
    del lines[:]
    for line in linestemp:
        lines.append(line)

def printtotals(totals):
    totalssorted = sorted(totals.items(), key=itemgetter(1), reverse=True)
    system('clear')
    for item in totalssorted:
        print(str(item[1]) + ' | ' + str(item[0]))
        # str(totals[item]) ) # + ' | ' + item)

##############################################
## MAIN FUNCTION
##############################################

def main():
    lines = []
    search(lines)
    cutips(lines)
    dumplist(lines)
    totals = Counter(lines)
    printtotals(totals)

main()
